"use client";

import { useState } from "react";
import ShareButtons from "../../../components/ShareButtons";

export default function AIRobotsGenerator() {
  const [bots, setBots] = useState({
    "GPTBot": true, // OpenAI's web crawler
    "ChatGPT-User": true, // ChatGPT web browsing
    "Google-Extended": true, // Google's Bard/Gemini crawler
    "ClaudeBot": true, // Anthropic's crawler
    "PerplexityBot": true, // Perplexity AI crawler
    "Omgilibot": true, // Webz.io (used by many LLMs)
    "FacebookBot": true, // Meta's Llama crawler
  });

  const toggleBot = (botName: keyof typeof bots) => {
    setBots(prev => ({ ...prev, [botName]: !prev[botName] }));
  };

  const generateRobotsTxt = () => {
    let output = "# AI Crawler robots.txt rules generated by SmallGEOTools\n\n";
    
    Object.entries(bots).forEach(([bot, isAllowed]) => {
      output += `User-agent: ${bot}\n`;
      output += isAllowed ? `Allow: /\n\n` : `Disallow: /\n\n`;
    });

    return output.trim();
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(generateRobotsTxt());
    alert("robots.txt copied to clipboard!");
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-6">
      <header className="mb-10 text-center">
        <h1 className="text-4xl font-extrabold text-gray-900 mb-4">AI Bot robots.txt Generator</h1>
        <p className="text-xl text-gray-600 max-w-2xl mx-auto">
          Control how Large Language Models (LLMs) crawl your site. Allow bots for GEO visibility, or block them to protect your content.
        </p>
      </header>

      <div className="grid md:grid-cols-2 gap-10">
        {/* Toggle Controls */}
        <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
          <h2 className="text-lg font-bold text-gray-900 mb-4 border-b pb-2">LLM Crawler Access</h2>
          <div className="space-y-4">
            {Object.entries(bots).map(([bot, isAllowed]) => (
              <div key={bot} className="flex items-center justify-between">
                <div>
                  <span className="font-semibold text-gray-800">{bot}</span>
                </div>
                <button
                  onClick={() => toggleBot(bot as keyof typeof bots)}
                  className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 ${
                    isAllowed ? "bg-green-500" : "bg-red-500"
                  }`}
                >
                  <span
                    className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                      isAllowed ? "translate-x-6" : "translate-x-1"
                    }`}
                  />
                </button>
              </div>
            ))}
          </div>
          <p className="text-xs text-gray-500 mt-6">
            * Green (Allow) means the bot can read your site to cite you in AI answers. Red (Disallow) prevents scraping.
          </p>
        </div>

        {/* Code Output */}
        <div className="bg-gray-900 rounded-xl p-6 relative shadow-lg flex flex-col justify-between h-full">
          <div>
            <h3 className="text-gray-300 text-sm font-semibold mb-4 uppercase tracking-wider">Your robots.txt</h3>
            <pre className="text-green-400 text-sm overflow-x-auto whitespace-pre-wrap font-mono bg-black p-4 rounded border border-gray-700">
              {generateRobotsTxt()}
            </pre>
          </div>
          <button 
            onClick={copyToClipboard}
            className="mt-6 w-full bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-4 rounded transition"
          >
            Copy Code
          </button>
        </div>
      </div>

      <ShareButtons title="AI Bot robots.txt Generator" urlPath="/tools/ai-robots-generator" />
    </div>
  );
}